# Travis CI config

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

language: c

branches:
  only:
    - master

script:
  - make
  - cd examples
  - chmod +x test.sh
  - res=0; for d in ./*/; do cd "$d"; ../../convpng; res=`expr $res + $?`; done; return $res

