# Travis CI config

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

language: c

branches:
  only:
    - master
    - convimg

script:
  - git submodule update --init --recursive
  - make clean
  - make
  - make release
  - cd ./test
  - chmod +x test.sh
  - ./test.sh; res=`expr $?`; return $res
